<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FeWo Template'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . 'css/style.css')
                        /**
                         * Fonts
                         */
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Engagement')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Julius+Sans+One')
                        /**
                         * CSS Libraries
                         */
                        ->prependStylesheet($this->basePath() . 'css/camera.css')
                        ->prependStylesheet($this->basePath() . 'css/jquery.lightbox.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
//                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . 'js/main.js')
            ->prependFile($this->basePath() . 'js/camera.min.js')
            ->prependFile($this->basePath() . 'js/jquery.easing.1.3.js')
//            ->prependFile($this->basePath() . 'js/jquery.mobile.customized.min.js')
//            ->prependFile($this->basePath() . '/js/jquery.lightbox.js')
//            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . 'js/jquery.min.js')
//            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <!-- start slider -->
    <div class="slider">
        <!-- #camera_wrap_1 -->
        <div class="fluid_container">
            <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
                <div  data-src="img/template/slider1.jpg">
                </div>
                <div  data-src="img/template/slider2.jpg">
                </div>
                <div  data-src="img/template/slider3.jpg">
                </div>
            </div><!-- #camera_wrap_1 -->
            <div class="clear"></div>
        </div>
        <!-- end #camera_wrap_1 -->
    </div>
    <!-- start header -->
    <div class="header_bg">
        <div class="wrap">
            <div class="wrapper1">
                <div class="menu">
                    <ul class="top-nav">
                        <li  class="active"><a href="index.html">HOME</a></li>
                        <li><a href="about.html">ABOUT</a></li>
                        <li><a class="hsubs" href="service.html">SERVICES</a></li>
                        <li><a href="contact.html">CONTACT</a></li>
                        <div class="clear"></div>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- start main -->
    <div class="main_bg">
        <div class="wrap">
            <div class="wrapper">
                <div class="main">
                    <?php echo $this->content; ?>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <!-- start footer -->
        <div class="footer_bg">
            <div class="wrap">
                <div class="wrapper">
                    <div class="footer">
                        <ul class="f_nav">
                            <li><a href="#">mail@agro_form.org</a></li>
                        </ul>
                        <div class="f_call">
                            <h3>: 	18 000 000 000</h3>
                        </div>
                        <div class="clear"></div>
                        <h2><a href="index.html">Agro farm</a></h2>
                        <div class="copy">
                            <p class="w3-link">© All Rights Reserved | Design by&nbsp; <a href="http://w3layouts.com/"> W3Layouts</a></p>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
<!--                <p>&copy; 2005 - --><?php //echo date('Y') ?><!-- by Zend Technologies Ltd. --><?php //echo $this->translate('All rights reserved.') ?><!--</p>-->