<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FeWo Template'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . 'css/style.css')
                        /**
                         * Fonts
                         */
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Engagement')
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Julius+Sans+One')
                        /**
                         * CSS Libraries
                         */
                        ->prependStylesheet($this->basePath() . 'css/camera.css')
                        ->prependStylesheet($this->basePath() . 'css/jquery.lightbox.css')
//                        ->prependStylesheet($this->basePath() . 'css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . 'css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . 'js/main.js')
            ->prependFile($this->basePath() . 'js/camera.min.js')
            ->prependFile($this->basePath() . 'js/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . 'js/jquery.mobile.customized.min.js')
            ->prependFile($this->basePath() . 'js/bootstrap.min.js')
            ->prependFile($this->basePath() . 'js/jquery.1.8.3.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
    <iframe width="100%" height="480" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
            src="https://maps.google.com/maps?layer=c&amp;panoid=1cHZwTAztrIAAAQWmqcHjQ&amp;ie=UTF8&amp;source=embed&amp;output=svembed&amp;cbp=13%2C0%2C%2C0%2C0"></iframe>
    <div class="header_bg">
        <div class="wrap">
            <div class="wrapper1">
                <div class="menu">
                    <?php
                    //erstelle drowdown navi mit 4 Hauptpunkten: Home, FeWo's, Umgebung, Kontakt
                    //FeWo' ist dropdown und wird aus der DB generiert
                    //Jede FeWo seite sieht vom layout her gleich aus, da sie aus der db aufgebaut werden
                    ?>
                    <ul class="top-nav">
                        <li  class="active"><a href="index.html">START</a></li>
                        <li><a href="loggia.html">FEWO LOGGIA</a></li>
                        <li><a class="hsubs" href="terrasse.html">FEWO TERRASSE</a></li>
                        <li><a href="umgebung.html">UMGEBUNG</a></li>
                        <div class="clear"></div>
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
    </div>
    <!-- start main -->
    <div class="main_bg">
        <div class="wrap">
            <div class="wrapper">
                <div class="main">
                    <?php echo $this->content; ?>
                </div>
                <div class="clear"></div>
            </div>
        </div>
        <!-- start footer -->
        <div class="footer_bg">
            <div class="wrap">
                <div class="wrapper">
                    <div class="footer">
                        <ul class="f_nav">
                            <li><a href="mailto:sylke-scheduikat@t-online.de">sylke-scheduikat@t-online.de</a></li>
                        </ul>
                        <div class="f_call">
                            <h3>: 038391 / 89572</h3>
                        </div>
                        <div class="clear"></div>
                        <h2><a href="index.html">Zeit zum Träumen</a></h2>
                        <div class="copy">
                            <p class="w3-link">© All Rights Reserved </a></p>
                        </div>
                    </div>
                </div>
                <div class="clear"></div>
            </div>
        </div>
    </div>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-50503516-1', 'fewo-traumzeit.de');
        ga('send', 'pageview');

    </script>
    <?php echo $this->inlineScript() ?>
    </body>
</html>
<!--                <p>&copy; 2005 - --><?php //echo date('Y') ?><!-- by Zend Technologies Ltd. --><?php //echo $this->translate('All rights reserved.') ?><!--</p>-->