<div class="content">
    <!-- start header -->
    <a href="index.html"><h2>Zeit zum Träumen</h2></a>
</div>
<!-- start slider -->
<div class="slider">
    <!-- #camera_wrap_1 -->
    <div class="fluid_container">
        <div class="camera_wrap camera_azure_skin" id="camera_wrap_1">
            <div  data-src="images/slider1.jpg"></div>
            <div  data-src="images/slider2.jpg"></div>
            <div  data-src="images/slider3.jpg"></div>
            <div  data-src="images/slider4.jpg"></div>
        </div><!-- #camera_wrap_1 -->
        <div class="clear"></div>
    </div>
    <!-- end #camera_wrap_1 -->
</div>
<div class="grids_of_3">
    <div class="grid_1_of_3 images_1_of_3">
        <img src="images/oben_wz.JPG">
        <div class="grids">
            <h3>Ferienwohnung Loggia</h3>
            <p>Genießen Sie Ihren Traumurlaub. Sonnen Sie sich auf Ihrer Loggia, oder nutzen Sie die 1000 m² gepflegte Wiese vor dem Haus. Machen Sie lange Spaziergänge am Strand, im Wald oder genießen Sie die Weite der Felder.Gerne auch mit Ihrem vierbeinigen Liebling.</p>
            <div class="button"><span><a href="loggia.html">Mehr</a></span></div>
        </div>
    </div>
    <div class="grid_1_of_3 images_1_of_3">
        <img src="images/unten_wz.JPG">
        <div class="grids">
            <h3>Ferienwohnung Terrasse</h3>
            <p>Genießen Sie Ihren Traumurlaub. Sonnen Sie sich auf der Terasse und lassen Sie Ihre Seele baumeln. Machen Sie lange Spaziergänge (mit Ihrem vierbeinigen Liebling?)und genießen Sie die saubere, frische Luft. Freuen Sie sich auf unseren Traumbonus.</p>
            <div class="button"><span><a href="terrasse.html">Mehr</a></span></div>
        </div>
    </div>
    <div class="grid_1_of_3 images_1_of_3">
        <img src="images/slider3.jpg">
        <div class="grids">
            <h3>Umgebung</h3>
            <p>Rügen bietet mit seiner einzigartigen Natur eine unvergessliche und einzigartige Umgebung!</p>
            <div class="button"><span><a href="umgebung.html">Mehr</a></span></div>
        </div>
    </div>
    <div class="clear"></div>
</div>